services:
  rnz-rss:
    build: .
    container_name: rnz-rss
    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:
      POLL_INTERVAL: 600
      DB_PATH: /app/data/rnz.db

    volumes:
      - ./data:/app/data
